// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: hlds_messages.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGameStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGameStatusRequest) Reset() {
	*x = GetGameStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hlds_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStatusRequest) ProtoMessage() {}

func (x *GetGameStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hlds_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGameStatusRequest) Descriptor() ([]byte, []int) {
	return file_hlds_messages_proto_rawDescGZIP(), []int{0}
}

type GameStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game    string `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Map     string `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	Players int32  `protobuf:"varint,4,opt,name=players,proto3" json:"players,omitempty"`
}

func (x *GameStatus) Reset() {
	*x = GameStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hlds_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatus) ProtoMessage() {}

func (x *GameStatus) ProtoReflect() protoreflect.Message {
	mi := &file_hlds_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatus.ProtoReflect.Descriptor instead.
func (*GameStatus) Descriptor() ([]byte, []int) {
	return file_hlds_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GameStatus) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *GameStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameStatus) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *GameStatus) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

type RconCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *RconCommand) Reset() {
	*x = RconCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hlds_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RconCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconCommand) ProtoMessage() {}

func (x *RconCommand) ProtoReflect() protoreflect.Message {
	mi := &file_hlds_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconCommand.ProtoReflect.Descriptor instead.
func (*RconCommand) Descriptor() ([]byte, []int) {
	return file_hlds_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RconCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RconCommandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RconCommandResult) Reset() {
	*x = RconCommandResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hlds_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RconCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconCommandResult) ProtoMessage() {}

func (x *RconCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_hlds_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconCommandResult.ProtoReflect.Descriptor instead.
func (*RconCommandResult) Descriptor() ([]byte, []int) {
	return file_hlds_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RconCommandResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_hlds_messages_proto protoreflect.FileDescriptor

var file_hlds_messages_proto_rawDesc = []byte{
	0x0a, 0x13, 0x68, 0x6c, 0x64, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x72, 0x75, 0x2e, 0x74, 0x6f, 0x6e, 0x36, 0x31, 0x38,
	0x2e, 0x68, 0x6c, 0x64, 0x73, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x16,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x27, 0x0a, 0x0b, 0x52, 0x63, 0x6f, 0x6e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x22, 0x2b, 0x0a, 0x11, 0x52, 0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x32,
	0x0a, 0x11, 0x72, 0x75, 0x2e, 0x74, 0x6f, 0x6e, 0x36, 0x31, 0x38, 0x2e, 0x68, 0x6c, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1b, 0x72, 0x75, 0x2e, 0x74, 0x6f, 0x6e, 0x36, 0x31, 0x38,
	0x2e, 0x68, 0x6c, 0x64, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hlds_messages_proto_rawDescOnce sync.Once
	file_hlds_messages_proto_rawDescData = file_hlds_messages_proto_rawDesc
)

func file_hlds_messages_proto_rawDescGZIP() []byte {
	file_hlds_messages_proto_rawDescOnce.Do(func() {
		file_hlds_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_hlds_messages_proto_rawDescData)
	})
	return file_hlds_messages_proto_rawDescData
}

var file_hlds_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hlds_messages_proto_goTypes = []interface{}{
	(*GetGameStatusRequest)(nil), // 0: ru.ton618.hlds.model.v1.GetGameStatusRequest
	(*GameStatus)(nil),           // 1: ru.ton618.hlds.model.v1.GameStatus
	(*RconCommand)(nil),          // 2: ru.ton618.hlds.model.v1.RconCommand
	(*RconCommandResult)(nil),    // 3: ru.ton618.hlds.model.v1.RconCommandResult
}
var file_hlds_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hlds_messages_proto_init() }
func file_hlds_messages_proto_init() {
	if File_hlds_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hlds_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hlds_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hlds_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RconCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hlds_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RconCommandResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hlds_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hlds_messages_proto_goTypes,
		DependencyIndexes: file_hlds_messages_proto_depIdxs,
		MessageInfos:      file_hlds_messages_proto_msgTypes,
	}.Build()
	File_hlds_messages_proto = out.File
	file_hlds_messages_proto_rawDesc = nil
	file_hlds_messages_proto_goTypes = nil
	file_hlds_messages_proto_depIdxs = nil
}
